name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

concurrency:
  group: workflow-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"

    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: devopsteamsdb/devopsteamsdb:teamtasks_${{ steps.date.outputs.date }}
        file: Dockerfile
        push: true

    - name: Docker Save
      run: docker save devopsteamsdb/devopsteamsdb:teamtasks_${{ steps.date.outputs.date }} | gzip > teamtasks_${{ steps.date.outputs.date }}.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release teamtasks_${{ steps.date.outputs.date }}
        body: |
          Release teamtasks_${{ steps.date.outputs.date }}
      
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        file: "teamtasks_${{ steps.date.outputs.date }}.gz"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
